#!/bin/bash
#SBATCH --job-name=trun_228
#SBATCH --partition=highmem_p
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=30
#SBATCH --mem=120G
#SBATCH --time=168:00:00
#SBATCH --export=NONE
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ul54354@uga.edu
 
cd $SLURM_SUBMIT_DIR
mkdir -p /lscratch/$ul54354/$SLURM_JOB_ID

#module
module load python/3.8.0

#script_py
python3 train_model.py
