#!/bin/bash
#SBATCH --job-name=deep_learning_accuracy
#SBATCH --partition=highmem_p
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=30
#SBATCH --mem=1G
#SBATCH --time=168:00:00
#SBATCH --export=NONE
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ul54354@uga.edu
 
cd $SLURM_SUBMIT_DIR
mkdir -p /lscratch/$ul54354/$SLURM_JOB_ID

# Load the module for Python and any other modules needed
module load python/3.8.0

# Run the Python script
python3 model_rumen_deep.py && cp model_accuracies.xlsx $SLURM_SUBMIT_DIR/ && rm -rf /lscratch/$ul54354/$SLURM_JOB_ID
